export default [
  {
    id: '01',
    user: 'Matheus Morillo',
    resolutionItem: '05/91',
    designation: '',
    denomination: 'Igreja São João',
    classification: '',
    conservationDegree: 'Alterado',
    conservationState: 'Regular',
    currentUsage: 'Igreja',
    originalUsage: 'Igreja',
    type: 'Igreja',
    addressLot: '',
    author: 'José da Silva',
    bibliographicalSources: '',
    otherInfos: '',
    observations: '',
    updatedAt: '2021-11-20T13:59',
    updatedBy: '2021-11-20T13:59',
  },
  {
    id: '02',
    user: 'José Claudio Pereira da Silva Santos',
    resolutionItem: '05/91',
    designation: '',
    denomination: 'Igreja São José',
    classification: '',
    conservationDegree: 'Alterado',
    conservationState: 'Ruim',
    currentUsage: 'Igreja',
    originalUsage: 'Igreja',
    type: 'Igreja',
    addressLot: '',
    author: 'José da Silva',
    bibliographicalSources: '',
    otherInfos: '',
    observations: '',
    updatedAt: '2021-11-20T13:59',
    updatedBy: '2021-11-20T13:59',
  },
  {
    id: '03',
    user: 'Raphael Nascimento',
    resolutionItem: '05/91',
    designation: '',
    denomination: 'Cinemark',
    classification: '',
    conservationDegree: 'Inalterado',
    conservationState: 'Ótimo',
    currentUsage: 'Cinema',
    originalUsage: 'Cinema',
    type: 'Entretenimento',
    addressLot: '',
    author: 'José da Silva',
    bibliographicalSources: '',
    otherInfos: '',
    observations: '',
    updatedAt: '2021-11-20T13:59',
    updatedBy: '2021-11-20T13:59',
  },
  {
    id: '04',
    user: 'Claudio Marino Pereira',
    resolutionItem: '05/91',
    designation: '',
    denomination: 'Estádio do Morumbi',
    classification: '',
    conservationDegree: 'Alterado',
    conservationState: 'Ótimo',
    currentUsage: 'Igreja',
    originalUsage: 'Igreja',
    type: 'Igreja',
    addressLot: '',
    author: 'José da Silva',
    bibliographicalSources: '',
    otherInfos: '',
    observations: '',
    updatedAt: '2021-11-20T13:59',
    updatedBy: '2021-11-20T13:59',
  },
  {
    id: '05',
    user: 'Jackson da Silva',
    resolutionItem: '05/91',
    designation: '',
    denomination: 'Praça Brasil',
    classification: '',
    conservationDegree: 'Alterado',
    conservationState: 'Regular',
    currentUsage: 'Parque',
    originalUsage: 'Praça',
    type: 'Praça',
    addressLot: '',
    author: 'José da Silva',
    bibliographicalSources: '',
    otherInfos: '',
    observations: '',
    updatedAt: '2021-11-20T13:59',
    updatedBy: '2021-11-20T13:59',
  },
]
